### ISSUE TITLE
Dead animation does not always play

### ISSUE THREAD

**Issue by sago007** [OpenArena/gamecode#12]
Some bug have slipped in there the dead animation does not always play. This can even happen to yourself if using cg_deathcam. I have not yet been able to reproduce it consistently and have no idea what causes it. At first I thought it was caused by a partially implemented animation system but the code did not suggest such.
![oa_dead_player_is_not_dead](https://cloud.githubusercontent.com/assets/2415098/21083046/23f58ba2-bfe8-11e6-80ea-e31c7fe597ab.jpg)

**Comment by leilei-** [comment]
cg_deathcam isn't fully implemented. Intended behavior that was planned:

0 - Off (Tilted view on the floor ala Quake 2, re-enabling otherwise unused code in cgame)
1 - On (default)
2 - Farther, freely rotatable camera (ala Tribes and Unreal)

I don't think death cam should ever tamper with animations though since it's largely involved with view code and I haven't seen any unplayed death anims myself yet.  I would almost pin this on an animation.cfg parsing bug

**Comment by sago007** [comment]
Thanks. I'll take a look at animation.cfg parsing soon.

It annoys me that I cannot reproduce it reliably.

**Comment by The-Gig** [comment]
First noticed doing these tests: http://openarena.ws/board/index.php?topic=5289.msg54419#msg54419
May somehow be related with such stuff (g_awardpushing 2, underwater)? Sago, when you did encounter it, was it in a similar environment? I haven't done further tests about it (e.g. if it is only on oax or also in 0.8.8) yet...

**Comment by The-Gig** [comment]
I haven't been able to reproduce the bug in 0.8.8. Maybe it's really related with g_awardpushing 2.... Uhm...

**Comment by sago007** [comment]
Might have been caused by g_awardpushing = 2. Apparently MOD_SUICIDE must gib. 
This explains why @The-Gig saw it a lot more than me.
From commit ba479f857f5b30c448776f7df148a532598bf4b4 this should no longer be relevant.
Closing this issue.
