### ISSUE TITLE
Are the game assets, models, textures open source?

### ISSUE THREAD

**Issue by github-yuzer** [OpenArena/gamecode#137]
Sorry to ask here, but the forums are closed :(

I'm wanting to use the models, textures for another Q3 engine based game mod. But I'm not sure if they are open source. Wanted to ask, so I know if I'll have to make stuff myself or if I'll be able to use these and modify them a bit to save time.

Thanks

**Comment by The-Gig** [comment]
AFAIK, all official oa assets are available under the GPLv2+ license, so you can reuse them following its terms. E.g. including a copy of the license, using them in a project with the same or a compatible license...Maybe using your own assets might give a better reputation to your mod, however using free ones is okay, as long as you respect their license.You can use OpenArena Discord to ask questions. :-)Il 1 novembre 2020 alle 2.24 github-yuzer <notifications@github.com> ha scritto:Sorry to ask here, but the forums are closed :(I'm wanting to use the models, textures for another Q3 engine based game mod. But I'm not sure if they are open source. Wanted to ask, so I know if I'll have to make stuff myself or if I'll be able to use these and modify them a bit to save time.Thanks-- You are receiving this because you are subscribed to this thread.Reply to this email directly or view it on GitHub:https://github.com/OpenArena/gamecode/issues/137

**Comment by NeonKnightOA** [comment]
All official OA assets are opensourced. Some of the files are nicked from Nexuiz, they actually requested both Yves Allaire (Evillair) and Simon O'Callaghan (simonoc/sock) for permission in order to use their textures as GPL in that game.

However, after 0.8.8, OA underwent a content reboot where every (or at least most) map, character, 3D model, etc, would be scrapped in favor of new content. This OFC meant that a lot of new assets had to be created from scratch. And the manpower is too low for such a task.

**Comment by TechnologyClassroom** [comment]
The README states the license, but the LICENSE file is missing. This prevents GitHub from properly parsing the license of the repository. Would you like me to submit a patch with the GPL-2.0-or-later license?

**Comment by NeonKnightOA** [comment]
> The README states the license, but the LICENSE file is missing. This prevents GitHub from properly parsing the license of the repository. Would you like me to submit a patch with the GPL-2.0-or-later license?

Go on. You might want to tag sago007, though.

**Comment by TechnologyClassroom** [comment]
Can this issue be closed now?
