### ISSUE TITLE
better grenade launcher

### ISSUE THREAD

**Issue by netpipe** [OpenArena/gamecode#144]
grenade launcher is useless most of the time it would be better to have a alt click to blow them or have proximity modes

**Comment by The-Gig** [comment]
That sounds like stuff for a mod (btw the "alternate fire" q3 mod works quite well with oa), as changing core q3 gameplay falls under "nottodo". And proximity mines are already a thing in oa (coming from Team Arena).

**Comment by NeonKnightOA** [comment]
What Gig said. For main OA the core gameplay isn't going to change. At all.

**Comment by netpipe** [comment]
maybe the damage can be increased then or have sensitivity mode for direct impact explosions.

**Comment by The-Gig** [comment]
There are a few mods around which allow to adjust some weapon parameters which are fixed in the base game, such as damage and reload time.
Idk what you mean about sensitivity mode. I think at the moment it's just if the coordinates of the grenades touch a player hitbox then explode before the time... Do you mean adding some extra radious around the grenate to sense collisions with players? I still think it better suits a mod, anyway maybe it might be implemented as a dmflags option to do not waste a precious cvar memory for it.

To be fair, there might be some more often requested features, such adding options for lowering a bit railgun and lighthning gun damage, and so far they have not been implemented I think mostly because devs feel that tweaking weapons behavior is stuff for mods.

**Comment by netpipe** [comment]
rather than bouncing off the floor 3 times it could just explode on impact

**Comment by The-Gig** [comment]
Oh, I get it. Making them more similar to rockets. I can see how it might make it easier to cause some degree of splash damage, although they would lose the ability to sneak them past corners in narrow corridors.
Anyway, I feel that's stuff for a mod.
