### ISSUE TITLE
[Feature] "dropweapon" command

### ISSUE THREAD

**Issue by NeonKnightOA** [OpenArena/gamecode#304]
This is a feature highly used in team games in competitive settings. It's also present in almost every other big name FPS, so it deserves an open thread.

I've tried porting it from both Aftershock and Ratmod, but it's too big of a job. -.- That, or I was really tired when I tried this.

In addition, I've observed both mods have flags regarding what players are allowed to throw, since they can also throw game objectives, items, and other stuff. Indeed, with the addition of dropweapon there should be a cvar that regulates what can be thrown. The commands will still be functional by default, as it makes no sense to be able to bind a key that does nothing.

**Comment by The-Gig** [comment]
Trying to link a Discord thread about this, I'm not sure whether this works for everyone:
<https://discord.com/channels/232322541912457218/1220766403699802143/1220766407332073492>
I already expressed some _personal considerations_ about Dropweapon there.

However, I'll try to add some kind of "**M2C/brainstorming**" also here, a bit relevant also for other kinds of items:
My thought is that you _can_ have keys to drop weapons, flags or runes, but in that case _there really should be_ a server cvar to specify whether or not dropping is allowed or not. While one is already at doing that, then he could make that cvar with multiple values (bitfield or not) to let server admins decide _what_ can be dropped in their server.

The ability of "binding a key that does nothing" through the GUI doesn't really risk to confuse players, because you can explain with mouseover text that the feature has to be enabled in the server in order to work. And you can also write a message in players' console whenever they press it in-game, like "Dropweapon is not enabled on this server.".

And _IMHO_ such features allow for new, interesting teamplay tactics, but can change _a lot_ the way the game is played, so they _should not_ be enabled by default. Id Software didn't want them, otherwise they would have put them in Q3A or TA. They didn't. _I believe that one of the strong points of Q3A is its simplicity_: adding extra layers of complexity shouldn't be the default.

Dropping stuff can really change the way you play. Dropping weapons can allow people _camping_ while teammates provide them with ammo, and campers can sometimes ruin fun. Being able to pass the flag to teammates is a _big_ help for attackers, as you can just pass the flag to a full healthy teammate instead of having to survive back to your base while your teammates try to _protect_ you.

About dropping _weapons_, maybe it doesn't sound very useful, though, considering there are plenty of them around the maps, and by default they respawn every 5 seconds (except for TDM mode, which has got a whole different way to manage weapon and ammo pickups). Keyboards keys aren't unlimited, so maybe only the most important things should be droppable, to save some key bindings? Example: would being able to drop a Personal Teleporter holdable or an armor Shard _really_ be worth one of your keyboard keys?

On a side note, dropping weapons with Elimination rules active would be risky, considering weapons don't respawn in that case. But of course a player has to take his own bald decisions, I guess. :)
