### ISSUE TITLE
[Bug] Choosing Team Deathmatch in the UI actually launch a FFA

### ISSUE THREAD

**Issue by Bishop-333** [OpenArena/gamecode#330]
Doesn't occur with oaxB53-r2, tested with the latest code

**Comment by The-Gig** [comment]
I confirm, testing with [2024-04-02_e2f919f.zip](https://files.poulsander.com/~poul19/public_files/oa/dev088/gamecode_nightly/openarena_gamecode_2024-04-02_e2f919f.zip), that TDM is still messed up.
In my case, I didn't even start the match through the GUI, I just loaded a map in console and changed gametype. It turned out to be a mix of FFA and TDM: no team-colored HUD, but "teams are tied" shown. The bot attacked me (causing damage only in case of g_friendlyFire active) AND sent me messages through team chat.

**Comment by NeonKnightOA** [comment]
Launching of new OAX version is on hold until this is solved.

**Comment by The-Gig** [comment]
Just for the record, adding screenshots. No team-colored status bar, no team overlay:
![shot0068](https://github.com/OpenArena/gamecode/assets/23258514/fdc5fcdc-8824-433c-a919-cbaacc11ad1f)
FFA-style score table. Bot attacking me and sending team chat messages:
![shot0069](https://github.com/OpenArena/gamecode/assets/23258514/f338b138-1b67-4feb-9dfa-a07b55b4c92f)

**Comment by NeonKnightOA** [comment]
I was too tired yesterday to commit changes to the repo. I'll work on this the whole weekend. I've reverted some code lines, but haven't found anything significant.

Might need to compare with vanilla 0.8.8 to see how the screen looked before.

**Comment by NeonKnightOA** [comment]
**I JUST FOUND OUT THE ERROR**

TDM wasn't considered for the Team Gametypes.

It should be solved in today's or tomorrow's nightly, but first that needs to be tested in order to be sure.

**Comment by NeonKnightOA** [comment]
Excellent!
